# Generated by Django 4.0.4 on 2022-07-25 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('eid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('emp_img', models.ImageField(null=True, upload_to='profilepics')),
                ('employee_name', models.CharField(max_length=80)),
                ('designation', models.CharField(max_length=80)),
                ('salary', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('experience', models.PositiveIntegerField(null=True)),
            ],
        ),
    ]
