# Generated by Django 4.0.6 on 2022-07-26 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_delete_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishes',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
